# Generated by Django 2.1 on 2019-11-20 05:23

from django.db import migrations, models
import djimage.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCompressImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', djimage.field.CompressImageField(upload_to='compress/')),
            ],
        ),
        migrations.CreateModel(
            name='TestDimensionImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', djimage.field.CompressImageField(upload_to='dimension/')),
            ],
        ),
    ]
